### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by jamescourtney** [jamescourtney/FlatSharp#13]
Set up some CI pipeline for pull requests!

**Comment by jafin** [comment]
I took a stab at this with AppVeyor.    I have a partially working build.
But there are a few issues I've been unable to solve.

## Build Pipeline erroring with dynamic code

The CI Pipeline builds the app but the dynamically generated code on the first pass will not compile for the app. On the second pass of a compile, the app will build fine, given that thee dynamic source code files already exist.    

I started to go down a rabbit hole seeing if it was something in the build tasks like https://stackoverflow.com/questions/1519177/gathering-outputs-from-an-msbuild-exec-task  but got nowhere.

## PackageReference in ExperimentalBenchmark

I also had to Update the PackageReference in ExperimentalBenchmark to Flatsharp.Compiler 3.0.0 (from 2.0.0)
```
 <PackageReference Include="FlatSharp.Compiler" Version="3.0.0">
```

If I did not do this I would get a build error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet C:\Users\jason\.nuget\packages\flatsharp.compiler\2.0.0\tools\netcoreapp2.1\FlatSharp.Compiler.dll D:\Data\_CodeOS\FlatSharp\src\ExperimentalBenchmark\Tests.fbs" exited with code -2147450740.	ExperimentalBenchmark	
C:\Users\jason\.nuget\packages\flatsharp.compiler\2.0.0\build\netcoreapp2.1\FlatSharp.Compiler.targets	15	
```
## Unit tests when targeting net47/net472 fail locally and CI.

Most of the unit tests fail for target net47. (I also tried moving the target to net472)  They all run successfully for netcoreapp2.1 

Most of the errors focus on the same error response:
```
Test method FlatSharpTests.Compiler.IncludeTests.CircularReferenceInclude threw exception: 
FlatSharp.FlatSharpCompilationException: FlatSharp failed to generate proper C# for your schema. Please see the list of errors for precise errors.
    at FlatSharp.RoslynSerializerGenerator.CompileAssembly(String sourceCode, Boolean enableAppDomainIntercept, Assembly[] additionalReferences) in D:\Data\_CodeOS\FlatSharp\src\FlatSharp\Serialization\RoslynSerializerGenerator.cs:line 205
   at FlatSharp.Compiler.FlatSharpCompiler.CreateCSharp(BaseSchemaMember rootNode) in D:\Data\_CodeOS\FlatSharp\src\FlatSharp.Compiler\FlatSharpCompiler.cs:line 278
   at FlatSharp.Compiler.FlatSharpCompiler.TestHookCreateCSharp(String fbsSchema, Dictionary`2 includes) in D:\Data\_CodeOS\FlatSharp\src\FlatSharp.Compiler\FlatSharpCompiler.cs:line 244
   at FlatSharpTests.Compiler.IncludeTests.CircularReferenceInclude() in D:\Data\_CodeOS\FlatSharp\src\FlatSharpTests\FlatSharpCompiler\IncludeTests.cs:line 109
```

Results of the tests can be seen here:  https://ci.appveyor.com/project/jafin/flatsharp/builds/32011013

If anyone can assist, I can try and correct this and submit a PR.

**Comment by jamescourtney** [comment]
Hey, I really appreciate you taking a look at this! Good find on the experimental benchmark reference. That's mostly been my playground for, well, experiments.

It's interesting that they don't pass for you locally, because they do for me. Do you see the same error as what's in AppVeyor?

For me, if I set a breakpoint on line 174 of RoslynSerializerGenerator.cs, I see this as the resolved location of "netstandard":

> Assembly Path='C:\Windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'

So, on my box, we're loading netstandard from the GAC. My guess is that "netstandard" is not in the GAC in the other locations.

I've created a provisional branch with an experimental fix. I really have no idea if it will work, but it should fall back to loading from the local directory if netstandard isn't found in the GAC. You can see the commits here: https://github.com/jamescourtney/FlatSharp/commits/net47Investigation

**Comment by jafin** [comment]
Thanks, that fixed it! Can pass CI now https://ci.appveyor.com/project/jafin/flatsharp
I'll send in a PR with the Appveyor config if it is useful to you merge it.

**Comment by jamescourtney** [comment]
Thanks again for taking care of this. This is the first PR by another person to this repo :)
