### ISSUE TITLE
Structs may not have serializers?

### ISSUE THREAD

**Issue by RyouBakura** [jamescourtney/FlatSharp#134]
Hi,

first of all thank you for making this awesome library. 

I've tried to run the schema below but the compiler complained that "Structs may not have serializers" because of the **sf_serializer** attribute:

>struct EnchantmentAttribute (fs_serializer, fs_nonVirtual) {
>       EnchantmentLevel:int;
>}

Does this mean that structs are only intended to be used with the runtime FlatSharp.dll?

**Comment by jamescourtney** [comment]
Structs can't be top-level objects in FlatSharp (though they can be in FlatBuffers). This is possible -- it's just not something anyone has asked me about before.

You can define:

```fbs
struct FooStruct (fs_nonVirtual) { Something:int; }
table FooTable(fs_serializer) { Struct:FooStruct; }
```

**Comment by jamescourtney** [comment]
> first of all thank you for making this awesome library.

You're welcome :)

**Comment by RyouBakura** [comment]
Thanks! The reason I asked is because I wanted to save a polymorph collection into a byte array.

Now after some experimenting with FlatSharp I came to the conclusion that the best way to do this is with a table with lots of union members. It looks a bit ugly but the output size is small and scales really well when there are lots of items in it:

```
union AnyType { 
    //...
}

table AttributeCollection (fs_serializer, fs_nonVirtual) {
    Id:int;
    Attribute1:AnyType;
    Attribute2:AnyType;
    Attribute3:AnyType;
    Attribute4:AnyType;
	// ...
}
```

Plus Union members can mix tables with structs the way you explained it, so this is perfect for me. ^__^

**Comment by jamescourtney** [comment]
Would FlatSharp supporting vectors of unions be at all interesting to you, or do you have a fixed number of attributes? I've refrained from implementing this because it is complex to do so (unions in general are *weird* in flatbuffers, and vectors of unions are even weirder).

**Comment by RyouBakura** [comment]
I'd definitely use it but it would be a luxury feature to have rather than a necessity (with varying but small and manageable collections).

**Comment by jamescourtney** [comment]
#136
