### ISSUE TITLE
Support for C# Structs

### ISSUE THREAD

**Issue by NVentimiglia** [jamescourtney/FlatSharp#146]
looks like the FlatBufferTableAttribute only supports objects of type class. Would enjoy using structs here.

**Comment by jamescourtney** [comment]
Flatsharp is built around subclassing types to implement serializers and parsers. This is a pretty foundational principle. I did at one point prototype using C# structs for FlatBuffer structs, but benchmarks actually favored the class-based approach.

The Google FlatBuffer library does indeed use structs for everything by default, so you might want to check there.
