### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by KingKnecht** [jamescourtney/FlatSharp#15]
Hi,

on the starting page the example of MonsterTable has attributes like:
      `[DefaultValue(100s)]`
but correct format is:
      `[DefaultValue((short)100)]`

next 
     `[FlatBufferItem(4, IsDeprecated = true)]`
does not compile, because of the "IsDeprecated" parameter.

and there is
     `public virtual Float Z { get; set; }`
with "F"loat instead of "f"loat.

**Comment by KingKnecht** [comment]
hmm, maybe it's because your package is not for .Net Framework.

**Comment by jamescourtney** [comment]
Thanks for the comment; I'll work on this!
