### ISSUE TITLE
Provide option for RPC service interfaces without explicitly building Grpc clients

### ISSUE THREAD

**Issue by TYoungSL** [jamescourtney/FlatSharp#175]
Example service interface;
```cs
interface IRpcService {
  System.Threading.Tasks.Task<ReturnType> RpcMethod(ParameterType request);
}
```

Example explicit interface implementation on Grpc client;
```cs
// existing generated Grpc client member
public virtual Grpc.Core.AsyncUnaryCall<ReturnType> RpcMethod(ParameterType request, Grpc.Core.Metadata? headers = null, System.DateTime? deadline = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
{
  checked
  {
    return RpcMethod(request, new Grpc.Core.CallOptions(headers, deadline, cancellationToken));
  }
}
// added explicit interface implementation of RPC service interface
System.Threading.Tasks.Task<ReturnType> IRpcService.RpcMethod(ParameterType request)
  => RpcMethod(request).ResponseAsync;
```

We'd like to have the option of generating these abstractions from fbs `rpc_service` declarations.

We have IPC/LPC use cases for these types of interfaces, as well as other RPC transports.

**Comment by jamescourtney** [comment]
For unary calls, I think this is a reasonable ask. However, how do you keep the gRPC-ness out of the interface for streaming interfaces?

A simpler alternative: FlatSharp generates everything as `partial`, so you can pretty easily add these extensions yourself using some partial classes that you declare.

```
rpc_service FooService
{
	SingleOperation(Empty) : Empty;
}
```

```c#
public static partial class FooService
{
    public partial class FooServiceClient : ISomeInterface
    {
         Task<Empty> ISomeInterface.SingleOperation(Empty empty) => this.SingleOperation(empty).ResponseAsync;
    }
}
```

**Comment by TYoungSL** [comment]
Just how I'd imagine it;

For streams, a `Stream` implementation wrapping `IClientStreamWriter<TRequest>` (`ClientRequestStream<TRequest, TResponse>`) for writing, for bidirectional streams a tuple including the former as well as an `IAsyncEnumerable` implementation wrapping `IAsyncStreamReader<TRequest,TResponse>` (`ServerRequestStream<TRequest>`) for reading.

`IAsyncEnumerable` support depends on .NET Standard 2.1, a fallback would be to include the interface (by NuGet dependency Microsoft.Bcl.AsyncInterfaces) in FlatSharp.Runtime built for framework versions prior, or to introduce the framework requirement as a warning or compiler flag.

**Comment by jamescourtney** [comment]
Instead of all of those interfaces, it may make more sense to just use `Channel<T>` and not define any interfaces:

```c#
public interface ISomeRpcService
{
      Task<TResponse> UnaryCall(TRequest request);

      ChannelReader<TResponse> ServerStreaming(TRequest request);

      Task<TResponse> ClientStreaming(ChannelReader<TRequest> request);

      ChannelReader<TResponse> BidirectionalStreaming(ChannelReader<TRequest> request);
}

```

The downside is that for client streaming, FlatSharp will need to spin up a background task to monitor the channel for inputs. However, that doesn't seem too tricky or evil, especially if the use is optional.

**Comment by TYoungSL** [comment]
`System.Threading.Channels.ChannelReader<T>` is .NET Standard 2.1, but LGTM.

**Comment by jamescourtney** [comment]
#177

**Comment by jamescourtney** [comment]
@TYoungSL -- Can you test out the package from this CI build: https://github.com/jamescourtney/FlatSharp/runs/2917916746?check_suite_focus=true

It should contain the changes that you want. You have to specify the `fs_rpcInterface` metadata on your definition with an optional interface name. 

```
// if the interface name is omitted, then the name will be IMyService
rpc_service MyService (fs_rpcInterface:"ISomeInterface")
{
   ...
}
```

The build is completely experimental, but should at least compile. Testing will be the tricky part of this, as there are threading issues, cancellation issues, and lots of error handling to get right. The generated code *looks* right to me, but lots of things do :)

**Comment by jamescourtney** [comment]
This is merged in #177. It will be included in the next feature release of FlatSharp (5.5.0) once the other features for that release are done as well. You can grab the linked CI build above or any of the builds from master after the merge to play with it early.

**Comment by TYoungSL** [comment]
Thanks, I'll be trying it out Monday for sure. 👍

**Comment by TYoungSL** [comment]
We're using the generated interfaces from the 5.5.0 CI artifact as components to service contracts.

Looks great! We can throw LPC/IPC wrappers around them just fine.

**Comment by jamescourtney** [comment]
That's good to hear. Glad it works well for you! If you don't run into any major issues, I'll publish the last build from master as version 5.5 in the next few days.

**Comment by jamescourtney** [comment]
> 
> 
> We're using the generated interfaces from the 5.5.0 CI artifact as components to service contracts.
> 
> Looks great! We can throw LPC/IPC wrappers around them just fine, and use Grpc when needed.

Does this mean that you no longer need #180?

**Comment by TYoungSL** [comment]
We still need a way to Pause/Resume, prioritize or control RPC flow.
```
      async Task IPipelineTransformerInterface.SendNodes(
        ChannelReader<TransformerNode> requestChannel,
        ChannelWriter<StirlingData.Status> responseChannel,
        CancellationToken token)
```
Ceasing buffering or queuing does not solve the problem of controlling actual transfer of already buffered data, unless I'm mistaken and there are no buffers.

**Comment by jamescourtney** [comment]
> Is the response stream or channel without buffers?

FlatSharp's code is a thin pump around those channels into gRPC's concept of async streams. How you define those channels is entirely up to you. If you're looking to avoid a flood of requests, then I'd suggest using `Channel.CreateBounded<T>(size)`, which will cap the size of the channel. Then you can always insert the highest priority item by using `channelWriter.WaitToWriteAsync()` to wait until the channel has space.

**Comment by jamescourtney** [comment]
5.5.0 is now on Nuget.
