### ISSUE TITLE
.net 6 preview 7 support

### ISSUE THREAD

**Issue by JurjenBiewenga** [jamescourtney/FlatSharp#192]
Hey,

I've been using FlatSharp with .net 6 preview for a while and it has worked great. However I tried to update to the latest preview and am now getting the following errors when building:
```
FlatSharp.Compiler.targets(35, 5): Failed to initialize CoreCLR, HRESULT: 0x80004005
FlatSharp.Compiler.targets(35, 5): [MSB3073] The command "dotnet /Users/user/.nuget/packages/flatsharp.compiler/5.6.0/tools/netcoreapp2.1/FlatSharp.Compiler.dll --nullable-warnings false --input "/Users/user/Git/project/Schemas/Schema.fbs" --output obj/Debug/netstandard2.0/ " exited with code 137.
```

The project with flatsharp in it is .netstandard 2.0 however that's referenced by a .net 6 project. This happens on both 5.2.0 and 5.6.0 of Flatsharp.

Actually don't think it's related to preview 7 since I managed to downgrade now and getting the same issue

**Comment by jamescourtney** [comment]
>Failed to initialize CoreCLR, HRESULT: 0x80004005

That looks like a .NET issue to me, not FlatSharp. Do you get the same error if you run the quoted command yourself?

**Comment by JurjenBiewenga** [comment]
Hey,
It indeed looks like a .NET issue, the timing and error was just very suspicious. Running that command also fails with the same error. 
Creating a new project (both console and asp) and running those does work.

**Comment by JurjenBiewenga** [comment]
Managed to resolve it by just removing all .net 6 things from my machine and then reinstalling it, really not quite sure what was going on. Thanks for the help!

**Comment by jamescourtney** [comment]
Cool -- I'm glad you got it working! Please feel free to reach out anytime FlatSharp is misbehaving. I'm always happy to listen to feature requests and try to fix bugs quickly.
