### ISSUE TITLE
FlatBufferUnion throws "InvalidOperationException" and fails to parse with Newtonsoft.Json

### ISSUE THREAD

**Issue by KillzXGaming** [jamescourtney/FlatSharp#21]
I have my tables setup like this. 

![uAEPOuZ](https://user-images.githubusercontent.com/13475262/69286699-e6faa100-0bc1-11ea-8341-e5062f70886e.png)

Which is based on this template i made (which does parse correctly)

![GIcCdIM](https://user-images.githubusercontent.com/13475262/69286745-13aeb880-0bc2-11ea-8095-94fb48703b1e.png)

When the file is deserialized, it will print out the exception. In turn it causes the json serializer to break due to "Error getting value from Item2, operation not valid to current state of object"

![Untitled](https://user-images.githubusercontent.com/13475262/69287173-53c26b00-0bc3-11ea-913f-4a6474c00b39.png)

The items appear to be null when previewed.

![Untitled](https://user-images.githubusercontent.com/13475262/69287070-e9112f80-0bc2-11ea-8a1c-a62f6449c0bf.png)

Which appears to give issues with json's deserializer. I am unsure if there's a particular setting i might need, or is this a potential issue with the library?

**Comment by jamescourtney** [comment]
Can you share code for a full repro? I'm not quite able to figure what's happening from the images here.
