### ISSUE TITLE
Unable to create runtime type model for Nullable

### ISSUE THREAD

**Issue by Exocomp** [jamescourtney/FlatSharp#23]
Hi there, are nullables supported if not can support be added.

I get the following exception:

`FlatSharp.TypeModel.InvalidFlatBufferDefinitionException: Unable to create runtime type model for Nullable`1`

```
    [FlatBufferTable]
    public class MyData
    {
        [FlatBufferItem(0)]
        public virtual int? Secret { get; set; }
    }
```

**Comment by jamescourtney** [comment]
Nullable types are not supported. It's something I can look into, but you should be able to specify a [DefaultValue] attribute to get around this.

**Comment by ngbrown** [comment]
Using `struct` in flatbuffers could be used to reliably support nullable types. A separate one for each scalar type, so `struct NullableShort { value:short }` etc.

These could be standardized in a `.fbs` file and then used for code gen as well.

The C# library for protocol buffers supports nullable this way.

**Comment by jamescourtney** [comment]
You're right -- this is possible, and I think your proposal comes pretty close. However, I don't want to include this by default for a few reasons...

1) FlatBuffers doesn't provide support for nullable primitives. If you want to build it, they give you the tools for that.
2) Another thing to keep in mind is that vectors cannot contain null, which necessitates the use of a HasValue property as well as the original value. However -- introducing this extra bool can throw off alignment as well. For int32's it adds 3 bytes of extra padding per item. For int64s it would add 7 bytes extra per item.
```
00: 1 0 0 0 1 0 0 0   // 4 byte alignment, Value = 1, HasValue = 1
08: 0 0 0 0 0 0 0 0  // Value = 0, HasValue = 0
12: 8 0 0 0 1 0 0 0  // Value = 8, HasValue = 1
```

3) This is pretty easy to accomplish without support from the framework. You can even define the type generically if you like and use implicit operator overloads to make it integrate more seamlessly. FlatSharp makes heavy use of generics in its own unit tests, though I don't usually advertise this functionality.

```c#
[FlatBufferStruct]
public class NullableStruct<T> where T : struct
{
	[FlatBufferItem(0)] public virtual T Value { get; set; }
	[FlatBufferItem(1)] public virtual bool HasValue { get; set; }

	public static implicit operator T? (NullableStruct<T> value)
	{
		if (value.HasValue) { return value.Value; }
		return null;
	}
	
	public static implicit operator NullableStruct<T>(T? item)
	{
		return new NullableStruct<T>
		{
			HasValue = item.HasValue,
			Value = item.GetValueOrDefault()
		};
	}
}

public static void Main()
{
        NullableStruct<int> nullable = 3;
	int? i = nullable;
}
```
