### ISSUE TITLE
FlatSharp output seemingly incompatible with Unity 2019

### ISSUE THREAD

**Issue by yewnyx** [jamescourtney/FlatSharp#243]
`#nullable disable` and `#nullable enable annotations` produce compilation errors, as do the `!` and `?` sprinkled throughout.

This was tested with both
`dotnet path\to\FlatSharp.Compiler.dll -i path\to\MySchema.fbs -o path\to\output --nullable-warnings=true` and `dotnet path\to\FlatSharp.Compiler.dll -i path\to\MySchema.fbs -o path\to\output --nullable-warnings=false` (or with the option omitted altogether), and produce output that can't be compiled in Unity 2019.4, whose language support is C# 7.3.

**Comment by jamescourtney** [comment]
FlatSharp targets C# 8.0, which looks like you need Unity version 2020.2 or greater.

**Comment by jamescourtney** [comment]
Thanks for that context. I don't have too much experience with Unity, unfortunately.

If you're wiling to use an older version of FlatSharp, I think 4.X uses C# 7.3 or less. It doesn't contain many of the newer features, but still has the compiler and most things you'd expect.

**Comment by yewnyx** [comment]
Appreciate the tip, I'll try that out!

**Comment by yewnyx** [comment]
D'oh! I did indeed forget that. Once I fixed expressions such as `index3Value is not null` to `index3Value != null`, it compiled. Thanks!

**Comment by jamescourtney** [comment]
Glad it worked. If you're willing to fiddle with the code, then removing the extra `?`'s and `!`'s shouldn't be too bad if you want to use the new version. There might be a few 8.0-only things, but probably not more than a handful.
