### ISSUE TITLE
Assembly reference errors on Unity 2021

### ISSUE THREAD

**Issue by yewnyx** [jamescourtney/FlatSharp#244]
There seem to be issues in Unity 2021.2 relating to System.Memory APIs in Unity, since it would seem to have some unholy union of .NET profiles to get Span<> functionality that it would otherwise have to wait a long time for from .NET Core: https://forum.unity.com/threads/2021-2-0b6-and-system-memory-readonlyspan-under-net-4-8.1152104/page-2

If my read is correct, an appropriate fix might be to include a binary built against netstandard2.1?

The linked thread refers to errors with protobufs and spans, so I would presume the class of errors are similar due to the shared history of protobufs and flatbuffers.

**Comment by yewnyx** [comment]
I've verified that a netstandard2.1 build does in fact fix the issues.

**Comment by jamescourtney** [comment]
Hey -- thanks for opening this (and fixing it!). 

Do you just need `FlatSharp.Runtime` to add `netstandard2.1`?

**Comment by jamescourtney** [comment]
I've fixed this in #248. 6.0.1 will be published later today.
