### ISSUE TITLE
Does it support pool creating?

### ISSUE THREAD

**Issue by liunliun** [jamescourtney/FlatSharp#263]
Hi jamescourtney,I think the flatshap can not deserialize from pool now.
So do you have a plan to support it in the future?

**Comment by jamescourtney** [comment]
There are no plans to support object pooling at this time. It was discussed in #164, and I decided not to pursue the feature. If you are having GC issues with FlatSharp, consider:
- [Value-type structs](https://github.com/jamescourtney/FlatSharp/wiki/FBS-Annotations-(FlatSharp-6.X)#fs_valuestruct)
- [Lazy deserialization](https://github.com/jamescourtney/FlatSharp/wiki/Deserialization-Modes)
