### ISSUE TITLE
Duplicate fbs filenames in different folders break compilation

### ISSUE THREAD

**Issue by njannink** [jamescourtney/FlatSharp#384]
When you have the following setup no code is generated for the fbs file in the LowRes sub-directory.

_Project_
- _Shapes_
  - shape.fbs
  - _LowRes_
    - shape.fbs
    
[project.zip](https://github.com/jamescourtney/FlatSharp/files/12196892/project.zip)

When I rename the shape.fbs file to shape.lowres.fbs then compilation passes

**Comment by jamescourtney** [comment]
Thanks for the bug! I'll take a look at this
