### ISSUE TITLE
Version conflict detected for Microsoft.CodeAnalysis.Common

### ISSUE THREAD

**Issue by rochapablo** [jamescourtney/FlatSharp#410]
Hello,

Is it possible to update the Microsoft.CodeAnalysis.CSharp and Microsoft.CodeAnalysis.CSharp.Workspaces to a new version?

**Comment by jamescourtney** [comment]
Which FlatSharp packages do you depend on? The FlatSharp compiler uses these packages, but it should be referenced as a build-time only assembly. If you are referencing the FlatSharp compiler from your code, something has probably gone wrong. Can you share a bit more detail?

**Comment by rochapablo** [comment]
I remember that after installed the last FlatSharp version I got dependency errors, but I lost the code. I'm gonna try again.
