### ISSUE TITLE
Running the Compiler

### ISSUE THREAD

**Issue by RotsiserMho** [jamescourtney/FlatSharp#44]
Hello, my C#/NuGet knowledge is a little weak, so I apologize if this is a dumb question. I'm using Visual Studio for macOS and I installed the NuGet package for the compiler. I'd like to setup a script to execute it from the command line to generate the C# code from my .fbs file. I assume I have to invoke `dotnet [something-or-other]`. I found [this documentation for .NET Core tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools), but running `dotnet tool list` does not show that the FlatSharp compiler is installed, although I do see it in the `[home]/.nuget/packages/flatsharp.compiler/3.0.0/tools/netcoreapp2.1` folder. How can I install the compiler package and invoke it from the command-line without referencing that specific path?

**Comment by jamescourtney** [comment]
If you include a ```FlatSharpSchema``` element in your .csproj, it should get invoked from the build. Take a look at the samples section in this repo to see some usages. My MSBuild knowledge is also not the strongest, so it's possible I've somehow borked the nuget package.
