### ISSUE TITLE
Clean build fails when using FlatSharp.Compiler

### ISSUE THREAD

**Issue by ccorsano** [jamescourtney/FlatSharp#45]
When using build-time generation, the first build fails as the newly generated .cs files are not added to the current compilation task.
Second build runs fine, which is the workaround I am currently using in my automation.

**Comment by jamescourtney** [comment]
Interesting, thanks. I think this may have to do with not adding the new CS project as a <Compile Include=""/> element. I've also always checked in an empty .cs file for it to overwrite. Thanks for bringing this up.

**Comment by jamescourtney** [comment]
This should be fixed by #55
