### ISSUE TITLE
Non-Generic .Serialize() / .Parse() possible?

### ISSUE THREAD

**Issue by joergbattermann** [jamescourtney/FlatSharp#47]
I tried to create a new Asp.Net Core (Mvc) Formatter using FlatSharp but unfortunately the Read*() / Write*() methods that need to be implemented (see [TextOutputFormatter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.textoutputformatter?view=aspnetcore-3.1) / [TextInputFormatter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.textinputformatter?view=aspnetcore-3.1)) to do so are all non-generic ones so gluing FlatSharp and Asp.Net Core formatters together is a bit.. difficult right now (or maybe I am just blind at first glance / attempt).

Is there any non-generic .Serialize() / Parse() already available with FlatSharp that I didn't see, is it maybe planned or not? Just trying to get an idea if that's something planned / doable / I can maybe help a bit with.

Thanks!
-Jörg

**Comment by jamescourtney** [comment]
Hi Jörg -- sorry for my delay in response. My day job has been consuming all the hours I have (and even some that I don't, at the moment).

Non-Generic invocations are certainly possible. Indeed, I do this from within the FlatSharp unit tests quite extensively:

```c#

        internal int ReflectionSerialize(object item, byte[] destination)
        {
            // unit test helper
            var method = this.GetType()
                .GetMethods(BindingFlags.NonPublic | BindingFlags.Instance)
                .Where(m => m.Name == nameof(this.SerializeInternal))
                .Single();

            var genericMethod = method.MakeGenericMethod(item.GetType());
            return (int)genericMethod.Invoke(this, new[] { item, destination });
        }

        internal object ReflectionParse(Type type, byte[] data)
        {
            // unit test helper
            var method = this.GetType()
                .GetMethods(BindingFlags.NonPublic | BindingFlags.Instance)
                .Where(m => m.Name == nameof(this.ParseInternal))
                .Single();

            var genericMethod = method.MakeGenericMethod(type);
            return genericMethod.Invoke(this, new[] { data });
        }
```

However, there's currently no API available that will do what you want in a support way. What you might consider doing is wrapping the ```ISerializer<T>``` interface with a non-generic equivalent that you can invoke on simple objects and cast internally to type T using semantics similar to what I do above. That at least means that you're not depending on some internal APIs.

**Comment by Eshva** [comment]
@jamescourtney why you don't make these 2 methods public? May be with rename to just Serialize and Parse.
Probably in my project I also do this reflection magic through generic private and internal methods in your class but it's a hack.
Why don't you open non-generic methods?

**Comment by jamescourtney** [comment]
This is something that I'd need to think about pretty carefully, and it's a little subtle. It's not quite as simple as just making those methods public. The reason being is that they use ```object.GetType()```. FlatSharp internally works by *subclassing* your table/struct/vector definitions, so if you deserialize:
```c#
object table = FlatBufferSerializer.Parse(typeof(MyTable), some data);
Debug.Assert(typeof(MyTable).IsAssignableFrom(table.GetType())); // will succeed
Debug.Assert(table.GetType() == typeof(MyTable)) // will fail, table is a subclass of MyTable

ModifyTable(table);
FlatBufferSerializer.Serialize(table, buffer); // different type. What explodes here? Anything?
```

So if we expose an API that depends on the actual type of the object instead of just the generic type, things may get weird in ways I haven't fully thought through. Because today, if you have a ```MyTable``` object, it doesn't matter if it's really a ```MyTable``` or if it's some Flatsharp-derived subclass of ```MyTable```, your code only ever sees it as ```MyTable```, and the generics all match up.

The first way that occurs to me to solve this is to add an interface to derived types:

```c#
public interface IFlatSharpDeserializedObject
{
    Type ActualType { get; } // different than base class?
}
```
Then these APIs could be smart about seeing this:
```c#
Type type;
if (object is IFlatSharpDeserializedObject subclass)
{
    type = subclass.ActualType;
}
else
{
   type = object.GetType();
}
```

**Comment by Eshva** [comment]
Namaste!
Probably I don't need this non-generic interface anymore. It's much simpler to move this reflection magic out of serializer. I need only make a generic method using generic (serialize or parse) method and known at the type message type.
In my code I do it a bit different but the logic the same. I have a registry of generic message type descriptors each of which is calling serialize or parse a generic way. I make a generic method using reflection. It's complicative for me to explain it. Much easer to show code:
```csharp
public interface IMessageTypeDescriptor<TMessageType> where TMessageType : class
{
  [NotNull]
  TMessageType Parse(Memory<byte> bytes);

  int Serialize([NotNull] TMessageType message, Span<byte> buffer);
}

public interface IMessageTypesRegistry
{
  [NotNull]
  Type GetType([NotNull] string messageTypeName);

  [NotNull]
  IMessageTypeDescriptor<TMessageType> GetDescriptor<TMessageType>([NotNull] string messageTypeName) where TMessageType : class;
}

public Task Execute(IPocket context)
{
  // ...
  // Code removed for brevity.
  var messageTypesRegistry = context.TakeOrThrow<IMessageTypesRegistry>(ContextKeys.PublicApi.MessageTypesRegistry);

  try
  {
    // Get message type to be serialized or parsed.
    var messageType = messageTypesRegistry.GetType(messageTypeName);
    // Make a method that will return typed descriptor.
    var getDescriptorMethod = typeof(IMessageTypesRegistry).GetMethod(nameof(IMessageTypesRegistry.GetDescriptor))!.MakeGenericMethod(messageType);
    // Get descriptor by using reflection method call.
    var descriptor = getDescriptorMethod.Invoke(messageTypesRegistry, new object?[] {messageTypeName});
    // Store it to use later to serialize/parse messages.
    context.Put(ContextKeys.Application.MessageTypeDescriptor, descriptor!);
  }
  catch (Exception exception)
  {
    // ...
    // Code removed for brevity.
  }
}
```

**Comment by jamescourtney** [comment]
#115
