### ISSUE TITLE
Schema file compilation fails for paths with spaces

### ISSUE THREAD

**Issue by vakkermans-triller** [jamescourtney/FlatSharp#78]
Hi all. I'm evaluating FlatSharp for a project and it looks great. I'm running into an issue that I think might be a bug.

When I try to build the sample project I run into an error whereby the .fbs files fail to compile:

```
The command "dotnet C:\Users\First Last\.nuget\packages\flatsharp.compiler\4.0.2\tools\netcoreapp2.1\FlatSharp.Compiler.dll C:\Users\First Last\source\3rdparty\FlatSharp\samples\Example2-SchemaFiles\SchemaFilesExample.fbs obj\Debug\netcoreapp3.1\" exited with code 1.

 * You intended to execute a .NET Core program, but dotnet-C:\Users\First does not exist.
```

It appears that this error occurs because the paths have spaces in them, and the arguments to the dotnet invocation aren't quoted.

I'm able to compile the sample project if I add `&quot;` in the right places in FlatSharp.Compiler.targets:
- `<CompilerInvocation>dotnet &quot;$(CompilerPath)&quot;</CompilerInvocation>`
- `<Exec Command="$(CompilerInvocation) &quot;%(FlatSharpSchema.fullpath)&quot;` ...

Would this be considered a bug or can I work around this in some way?

This is Flatsharp 4.0.2, Visual Studio 2019.

Happy to raise a PR.

**Comment by jamescourtney** [comment]
Everything is working okay now? I'm curious what the issue was, if you don't mind sharing.
