### ISSUE TITLE
Include different namespaces

### ISSUE THREAD

**Issue by FinalFortune** [jamescourtney/FlatSharp#80]
The compiler doesn't seem to generate the code if the items used from the Include are in a different namespace.

__
e.g.

A.fbs:
```
Include "B.fbs"
namespace my.namespace.stuff;

table Bar {
  MyFoo:Foo
}
```

B.fbs 
```
namespace my.namespace.otherstuff; 

table Foo {
}
```

Compiler unable to resolve Foo in A.fbs

**Comment by Eshva** [comment]
You need to use "full name" of the type.
```
Include "B.fbs";
namespace my.namespace.stuff;

table Bar {
  MyFoo:my.namespace.otherstuff.Foo;
}
```
