### ISSUE TITLE
[Compiler]: Plugin model for extensibility when using compiler

### ISSUE THREAD

**Issue by jamescourtney** [jamescourtney/FlatSharp#96]
Customers should be able to specify their own type model containers or facades when invoking the Flatsharp compiler. This will (probably) need to take place in the form of a plugin that the compiler can load and invoke to request the type model container it should use.

**Comment by TYoungSL** [comment]
This might be a convenient way for us to expose .NET intrinsic types for simple scalar fields.

**Comment by jamescourtney** [comment]
`flatc`, the official compiler has a newer feature to dump the contents of the FBS file into a structured FlatBuffer schema. So, instead of telling it to generate C#, you tell it to build the schema, and it generates a FlatBuffer file representing the schema that it just parsed.

Parsing an IDL file like FBS is nontrivial today, and there are always lots of "gotchas". FlatSharp's current implementation generally maps well to the `flatc` implementation, but it's starting to reach its limits, and a rewrite is needed.

To take advantage of `flatc`, FlatSharp 6.0.0 will begin using the output of `flatc`'s IDL parse to generate C#. The rest will remain the same. FlatSharp will continue to support all the things it did in 5.7.1. There will just be a different parser in front of it.

This has lots of advantages:
- No more cases where FlatSharp would compile something but `flatc` wouldn't.
- No more cases where FlatSharp interprets the IDL differently (there was a bug at one point around enums starting at 0 or 1)
- Less to maintain in FlatSharp. No more grammar, validation, etc.

But also a few drawbacks:
- Extensibility items like this will be less harder.
- FlatSharp is less able to support schema extensions.
