### ISSUE TITLE
[Flatsharp] Support for native integers in serializers?

### ISSUE THREAD

**Issue by jamescourtney** [jamescourtney/FlatSharp#99]
Investigate support for nint in serializers. Does this help performance at all?

**Comment by jamescourtney** [comment]
Out of scope for 5.0, as this needs C# 9.

**Comment by jamescourtney** [comment]
Also needs ```Span<T>``` to accept ```nint``` arguments for slice, etc.

**Comment by TYoungSL** [comment]
It's a shame Span is stuck on ints. We've made a library that is 100% compatible with Span/ReadOnlySpan, is the same size as Span, uses Span internally, and performs almost the same (within margin of error) that uses `nuint`s... not `nint`s though, might later as 1.84e+19 is overkill and many operations could use nints; the lack of negative value checks is a very minor performance improvement.

https://github.com/StirlingLabs/BigSpans.Net

**Comment by jamescourtney** [comment]
Agree completely on Span being stuck on int. It seems like a relatively large miss to me, but they don't ask me about the APIs in .NET :)

That's an interesting library. I haven't seen `InlineIL` before -- that's a clever way of writing IL directly in C#. Thanks for sharing!
